### ISSUE TITLE
[1.9] Molding station crash

### ISSUE THREAD

**Issue by xiaoschannel** [EXTER7/Foundry#44]
Hi. Sometimes when i move mouse over the grid, game crashes. Here's one example:

java.lang.ArrayIndexOutOfBoundsException: 37
    at exter.foundry.tileentity.TileEntityMoldStation.getGridSlot(TileEntityMoldStation.java:126)
    at exter.foundry.gui.GuiMoldStation.func_73863_a(GuiMoldStation.java:170)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:317)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1072)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

The environment i used is 1865 forge, 1.3 substratum, 2.0 alpha 1 foundary.

**Comment by EXTER7** [comment]
This has been fixed in the Alpha 2 release.
