### ISSUE TITLE
Crash when opening Creative Search Items menu

### ISSUE THREAD

**Issue by asiekierka** [EXTER7/Foundry#9]
java.lang.NullPointerException
    at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:115)
    at net.minecraftforge.fluids.Fluid.getID(Fluid.java:182)
    at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:27)
    at exter.foundry.item.ItemRefractoryFluidContainer.func_77633_a(ItemRefractoryFluidContainer.java:136)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_74228_j(GuiContainerCreative.java:374)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_74227_b(GuiContainerCreative.java:589)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73879_b(GuiContainerCreative.java:490)
    at net.minecraft.client.gui.GuiScreen.func_73867_d(SourceFile:132)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73867_d(GuiContainer.java:1009)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73867_d(GuiContainerCreative.java:608)
    at net.minecraft.client.gui.GuiScreen.func_73862_m(SourceFile:107)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1566)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by EXTER7** [comment]
Can you provide a full crash report? This crash seems to come from inside Forge.

**Comment by asiekierka** [comment]
http://paste.ubuntu.com/6960714/

It is a bug inside Forge, it also only appears in SMP when I click "Search Items". It works fine in SSP. Sadly, Forge definitely won't fix it for 1.6.4, so it would be nice if we could figure out a way to fix this within Foundry.
